<?php
if (($drone_media_slider_sc = drone_media_get_theme_option('front_page_title_shortcode')) != '' && strpos($drone_media_slider_sc, '[')!==false && strpos($drone_media_slider_sc, ']')!==false) {

	?><div class="front_page_section front_page_section_title front_page_section_slider front_page_section_title_slider"><?php
		// Add anchor
		$drone_media_anchor_icon = drone_media_get_theme_option('front_page_title_anchor_icon');	
		$drone_media_anchor_text = drone_media_get_theme_option('front_page_title_anchor_text');	
		if ((!empty($drone_media_anchor_icon) || !empty($drone_media_anchor_text)) && shortcode_exists('trx_sc_anchor')) {
			echo do_shortcode('[trx_sc_anchor id="front_page_section_title"'
											. (!empty($drone_media_anchor_icon) ? ' icon="'.esc_attr($drone_media_anchor_icon).'"' : '')
											. (!empty($drone_media_anchor_text) ? ' title="'.esc_attr($drone_media_anchor_text).'"' : '')
											. ']');
		}
		// Show slider (or any other content, generated by shortcode)
		echo do_shortcode($drone_media_slider_sc);
	?></div><?php

} else {

	?><div class="front_page_section front_page_section_title<?php
				$drone_media_scheme = drone_media_get_theme_option('front_page_title_scheme');
				if (!drone_media_is_inherit($drone_media_scheme)) echo ' scheme_'.esc_attr($drone_media_scheme);
				echo ' front_page_section_paddings_'.esc_attr(drone_media_get_theme_option('front_page_title_paddings'));
			?>"<?php
			$drone_media_css = '';
			$drone_media_bg_image = drone_media_get_theme_option('front_page_title_bg_image');
			if (!empty($drone_media_bg_image)) 
				$drone_media_css .= 'background-image: url('.esc_url(drone_media_get_attachment_url($drone_media_bg_image)).');';
			if (!empty($drone_media_css))
				echo ' style="' . esc_attr($drone_media_css) . '"';
	?>><?php
		// Add anchor
		$drone_media_anchor_icon = drone_media_get_theme_option('front_page_title_anchor_icon');	
		$drone_media_anchor_text = drone_media_get_theme_option('front_page_title_anchor_text');	
		if ((!empty($drone_media_anchor_icon) || !empty($drone_media_anchor_text)) && shortcode_exists('trx_sc_anchor')) {
			echo do_shortcode('[trx_sc_anchor id="front_page_section_title"'
											. (!empty($drone_media_anchor_icon) ? ' icon="'.esc_attr($drone_media_anchor_icon).'"' : '')
											. (!empty($drone_media_anchor_text) ? ' title="'.esc_attr($drone_media_anchor_text).'"' : '')
											. ']');
		}
		?>
		<div class="front_page_section_inner front_page_section_title_inner<?php
			if (drone_media_get_theme_option('front_page_title_fullheight'))
				echo ' drone_media-full-height sc_layouts_flex sc_layouts_columns_middle';
			?>"<?php
				$drone_media_css = '';
				$drone_media_bg_mask = drone_media_get_theme_option('front_page_title_bg_mask');
				$drone_media_bg_color = drone_media_get_theme_option('front_page_title_bg_color');
				if (!empty($drone_media_bg_color) && $drone_media_bg_mask > 0)
					$drone_media_css .= 'background-color: '.esc_attr($drone_media_bg_mask==1
																		? $drone_media_bg_color
																		: drone_media_hex2rgba($drone_media_bg_color, $drone_media_bg_mask)
																	).';';
				if (!empty($drone_media_css))
					echo ' style="' . esc_attr($drone_media_css) . '"';
		?>>
			<div class="front_page_section_content_wrap front_page_section_title_content_wrap content_wrap">
				<?php
				// Caption
				$drone_media_caption = drone_media_get_theme_option('front_page_title_caption');
				if (!empty($drone_media_caption) || (current_user_can('edit_theme_options') && is_customize_preview())) {
					?><h1 class="front_page_section_caption front_page_section_title_caption front_page_block_<?php echo !empty($drone_media_caption) ? 'filled' : 'empty'; ?>"><?php echo wp_kses_post($drone_media_caption); ?></h1><?php
				}
			
				// Description (text)
				$drone_media_description = drone_media_get_theme_option('front_page_title_description');
				if (!empty($drone_media_description) || (current_user_can('edit_theme_options') && is_customize_preview())) {
					?><div class="front_page_section_description front_page_section_title_description front_page_block_<?php echo !empty($drone_media_description) ? 'filled' : 'empty'; ?>"><?php echo wp_kses_post(wpautop($drone_media_description)); ?></div><?php
				}
				
				// Buttons
				if (drone_media_get_theme_option('front_page_title_button1_link')!='' || drone_media_get_theme_option('front_page_title_button2_link')!='') {
					?><div class="front_page_section_buttons front_page_section_title_buttons"><?php
						drone_media_show_layout(drone_media_customizer_partial_refresh_front_page_title_button1_link());
						drone_media_show_layout(drone_media_customizer_partial_refresh_front_page_title_button2_link());
					?></div><?php
				}
				?>
			</div>
		</div>
	</div>
	<?php
}